### ISSUE TITLE
Metadata documentation

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/TBEP_Habitat_Restoration#2]
We should create some metadata for the `Habitat_Restoration_Clean.csv` dataset, basically a [data dictionary](https://tbep-tech.github.io/data-management-sop/keys.html#dict) for the columns.  I'll need this info for getting it in the KNB archive.  I'll take a stab at getting it started.

**Comment by kflahertywalia** [comment]
I'm pretty sure that we can use the [NEPORT definitions](url) for all except the added columns.

**Comment by kflahertywalia** [comment]
OK, that link didn't work: https://docs.google.com/document/d/1Qbn0PuLWPvyI4HLtQCfSR797Cbky3cpw/edit?usp=drive_link&ouid=102375550280551412077&rtpof=true&sd=true

**Comment by fawda123** [comment]
Well shoot, that's what I get for being proactive... I just made up some column descriptions. It's not critical they follow the NEPORT definitions, so long as the description is reasonable.  Can you please have a look at the draft metadata file and edit when you're able? No rush.

https://github.com/tbep-tech/TBEP_Habitat_Restoration/blob/main/metadata.csv

**Comment by kflahertywalia** [comment]
Revisions added - also after going through the metadata, we can delete two columns from the "clean" file that are either empty or repetitive with other columns (Total_Cost and TBEP_Notes)
