### ISSUE TITLE
Create KNB archive for clean dataset

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/TBEP_Habitat_Restoration#3]
@kflahertywalia, please let me know when you've finished your edits to the clean dataset.  I can upload all data up through 2022 to KNB when that's done.

**Comment by kflahertywalia** [comment]
Edits are complete to account for missing data in the "PrimaryHabitat" column and to append 2023 data. Ready to add to a repository and upload to the WaterAtlas.
