### ISSUE TITLE
Integrate with smartsheets

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/TBEP_Habitat_Restoration#4]
Form entry for GPRA is here: https://app.smartsheet.com/b/form/c06876a6764942eba7d07adaaac5d196

Need to build a processing script that pulls entries from smartsheets and adds to the "official" dataset.

**Comment by kflahertywalia** [comment]
I'll work on the processing script.

**Comment by fawda123** [comment]
Adding some comments for the record... once GPRA from smartsheets is added to the "official" dataset, it can be sent to Water Atlas as is, they seem to have a workflow for pulling out relevant info for the map summary and the current version already has extraneous columns which aren't a big deal.  The `restoration.csv` sheet will feed the workflow on the [habitat-report-card](https://github.com/tbep-tech/habitat-report-card) repo.

For pulling sheets from smartsheet, something like this:

```r
library(remotes)
install_github('fawda123/rsmartsheet'))
library(rsmartsheet)

smrkey <- Sys.getenv("smartsheets_key")
set_smartsheet_api_key(smrkey)

gpra <- get_sheet_as_csv('name_of_sheet') %>% 
  textConnection %>% 
  read.table(sep = ',', header = T)
```
You'll need to install the `rsmartsheet` package, then get an API key from smartsheet and add it to your R environment.  Easy to do, but not clear if you've never done it.  You can generate an API key/token from your personal setttings -> API access in smartsheet, then just add it to your R environment using `usethis::edit_r_environ()`.

**Comment by fawda123** [comment]
working on it 96752578c801536c8c786b9e6136037e82fd640a
